# Remove the version line entirely and use this simplified version:

services:
  # Frontend Web Service
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - lab-network

  # Backend API Service
  api:
    build: 
      context: ./api
      dockerfile: ../Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    networks:
      - lab-network
    volumes:
      - ./api:/app:ro

  # Database Service (using SQLite instead of MySQL for simplicity)
  database:
    image: nginx:alpine  # Using nginx as a simple placeholder
    ports:
      - "3306:80"
    networks:
      - lab-network

  # Redis Cache
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge